### ISSUE TITLE
Error when getting Discord Player Data

### ISSUE THREAD

**Issue by Wingdingderp** [BoredManCodes/SMP-API#2]
I am getting this long list of warnings and errors when I try to get player data through Discord:

```
[23:17:55 INFO]: [SMP-API] A request was made to access Wingdingderp's player data
[23:19:06 WARN]: Exception in thread "pool-13-thread-9" java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[23:19:06 WARN]: 	at SMP-API-2.0.3.jar//net.boredman.routes.DiscordRoute.lambda$new$0(DiscordRoute.java:27)
[23:19:06 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterImpl.handle(FilterImpl.java:100)
[23:19:06 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayer.filter(FilterLayer.java:41)
[23:19:06 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayerHandler.handle(FilterLayerHandler.java:36)
[23:19:06 WARN]: 	at SMP-API-2.0.3.jar//express.Express.lambda$listen$3(Express.java:372)
[23:19:06 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:06 WARN]: 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
[23:19:06 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:06 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
[23:19:06 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:06 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
[23:19:06 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:19:06 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:19:06 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:19:40 WARN]: Exception in thread "pool-13-thread-10" java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[23:19:40 WARN]: 	at SMP-API-2.0.3.jar//net.boredman.routes.DiscordRoute.lambda$new$0(DiscordRoute.java:27)
[23:19:40 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterImpl.handle(FilterImpl.java:100)
[23:19:40 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayer.filter(FilterLayer.java:41)
[23:19:40 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayerHandler.handle(FilterLayerHandler.java:36)
[23:19:40 WARN]: 	at SMP-API-2.0.3.jar//express.Express.lambda$listen$3(Express.java:372)
[23:19:40 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:40 WARN]: 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
[23:19:40 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:40 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
[23:19:40 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:19:40 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
[23:19:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:19:40 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:19:40 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:20:02 WARN]: Exception in thread "pool-13-thread-11" java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[23:20:02 WARN]: 	at SMP-API-2.0.3.jar//net.boredman.routes.DiscordRoute.lambda$new$1(DiscordRoute.java:71)
[23:20:02 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterImpl.handle(FilterImpl.java:100)
[23:20:02 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayer.filter(FilterLayer.java:41)
[23:20:02 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayerHandler.handle(FilterLayerHandler.java:36)
[23:20:02 WARN]: 	at SMP-API-2.0.3.jar//express.Express.lambda$listen$3(Express.java:372)
[23:20:02 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:20:02 WARN]: 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
[23:20:02 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:20:02 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
[23:20:02 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:20:02 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
[23:20:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:20:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:20:02 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:23:04 WARN]: Exception in thread "pool-13-thread-13" java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
[23:23:04 WARN]: 	at SMP-API-2.0.3.jar//net.boredman.routes.DiscordRoute.lambda$new$0(DiscordRoute.java:27)
[23:23:04 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterImpl.handle(FilterImpl.java:100)
[23:23:04 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayer.filter(FilterLayer.java:41)
[23:23:04 WARN]: 	at SMP-API-2.0.3.jar//express.filter.FilterLayerHandler.handle(FilterLayerHandler.java:36)
[23:23:04 WARN]: 	at SMP-API-2.0.3.jar//express.Express.lambda$listen$3(Express.java:372)
[23:23:04 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:23:04 WARN]: 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
[23:23:04 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:23:04 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
[23:23:04 WARN]: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
[23:23:04 WARN]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
[23:23:04 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:23:04 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:23:04 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Wingdingderp** [comment]
Could I fix it by adding an older version of DiscordSRV?

**Comment by BoredManCodes** [comment]
Absolutely

**Comment by Wingdingderp** [comment]
Off the top of your head, do you happen to know what version that would be?

**Comment by Wingdingderp** [comment]
This Commit modified AccountLinkManager a bunch in DiscordSRV

[](https://github.com/DiscordSRV/DiscordSRV/commit/d581ed1bdd2eaf23a43f6f29c58a0c75cb2a05d7)

**Comment by BoredManCodes** [comment]
Closing this for now since a fix has been pushed to . Happy to reopen if it still reproduces on the latest build.

**Comment by BoredManCodes** [comment]
A fix has been pushed to `main`.

Changes include:
- updated the Discord route handling
- corrected `/discord/id/:id` so it treats the value as a UUID
- marked `DiscordSRV` as a provided dependency instead of bundling it

If you're still hitting this, please grab the latest build from `main` and test it with your current DiscordSRV version. If it still breaks, send me the DiscordSRV version and the new stack trace and I’ll dig further.
